"""
A mocking gRPC client interface for tests.

Usage:
    1. Suppose you want to test the RPC function `create_user` of gRPC
       client interface `UserInterface`, then the test may look like:
        ```
        import unittest
        from user_module import UserInterface
        class TestUserInterface(unittest.TestCase):
            user_inter = UserInterface(...)
            def test_create_user(self):
                result = self.user_inter.create_user(name='russellluo')
                self.assertEqual(result, 0)
        ```
       The above test will pass if the real gRPC server is running, but
       running a gRPC server for tests is cumbersome.
    2. Use `Mocker` to simply the test environment
        ```
        import unittest
        from user_module import UserInterface
        from mocker_module import Mocker
        class TestUserInterface(unittest.TestCase):
            user_inter = Mocker(UserInterface(...))
            def test_create_user(self):
                result = self.user_inter.create_user(name='russellluo')
                self.assertEqual(result, 0)
        ```
        1) First, run the test once, by interacting with the real gRPC server
        2) Then, you will find that the class `Mocker` in the module file
           `mocker_module` is changed magically
        3) Afterwards, you can run the test alone as many times as you wish,
           and the test will always pass without any interaction with the real
           gRPC server

Internals:
    When interacting with the real gRPC server, the mocking class
    `Mocker` can automatically record the real input/output data of
    each call of each RPC function, and finally `Mocker` will change
    itself to be a complete replacement for the real gRPC interface.
"""
import pickle
import functools
import os
import pprint
from collections import defaultdict


def record(data, method):
    @functools.wraps(method)
    def decorator(*args, **kwargs):
        params = pickle.dumps(args) + pickle.dumps(kwargs)
        method_data = data[method._method.decode().split('/')[-1]]
        if params not in method_data:
            result = method(*args, **kwargs)
            method_data[params] = pickle.dumps(result)
        return pickle.loads(method_data[params])
    return decorator


class Mocker(object):

    def __init__(self, target):
        self._data = getattr(self, '_fake_data', defaultdict(dict))
        for attr_name in dir(target):
            if not attr_name.startswith('_'):
                target_method = getattr(target, attr_name)
                recordable_func = record(self._data, target_method)
                setattr(self, attr_name, recordable_func)

    def __del__(self):
        mocker_file = os.path.abspath(__file__)
        with open(mocker_file, 'r') as f:
            content = f.read()

        with open(mocker_file, 'w') as f:
            fake_data_comment = '# Generated fake data'
            mocker_body = ''.join(content.rpartition(fake_data_comment)[:-1])
            f.write(mocker_body)

            fake_data_string = pprint.pformat(dict(self._data))
            f.write('\n    _fake_data = ' + fake_data_string)

            # Generated fake data
    _fake_data = {'Analyze': {b'\x80\x03chydro_serving_grpc.monitoring.api_pb2\nExecutionInformation\nq\x00)Rq\x01}q\x02X\n\x00\x00\x00serializedq\x03B;\x01\x00\x00\n\xb1\x01\n@\n5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04\x1a\x07predict\x12\x1a\n\x08Day Mins\x12\x0e\x08\x02\x12\x002\x08\x9a\x99\x99\x99\x999a@\x12\x14\n\tDay Calls\x12\x07\x08\t\x12\x00R\x01a\x12\x1f\n\rVMail Message\x12\x0e\x08\x02\x12\x002\x08\x9a\x99\x99\x99\x99\x99\xb9?\x12\x1a\n\x0eAccount Length\x12\x08\x08\t\x12\x00R\x02\xba\x01\x1a\x19\n\x17\n\x05Churn\x12\x0e\x08\x02\x12\x002\x08\x00\x00\x00 \xe58\x90?"j\x08!\x12\x07predict\x1a$3e580a13-174e-4c43-9b77-1b51fff4086e"5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04(\x01q\x04sb\x85q\x05.\x80\x03}q\x00.': b'\x80\x03cg'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'oogl'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'e.pr'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'otob'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'uf.e'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'mpty'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'_pb2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\nEmp'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'ty\nq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x00)Rq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x01}q\x02'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'X\n\x00\x00'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x00ser'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'iali'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'zedq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x03C\x00q'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x04sb.',
             b'\x80\x03chydro_serving_grpc.monitoring.api_pb2\nExecutionInformation\nq\x00)Rq\x01}q\x02X\n\x00\x00\x00serializedq\x03B;\x01\x00\x00\n\xb1\x01\n@\n5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04\x1a\x07predict\x12\x1a\n\x08Day Mins\x12\x0e\x08\x02\x12\x002\x08\xcd\xcc\xcc\xcc\xccL\\@\x12\x14\n\tDay Calls\x12\x07\x08\t\x12\x00R\x01`\x12\x1f\n\rVMail Message\x12\x0e\x08\x02\x12\x002\x08\x00\x00\x00\x00\x00\x009@\x12\x1a\n\x0eAccount Length\x12\x08\x08\t\x12\x00R\x02\x84\x01\x1a\x19\n\x17\n\x05Churn\x12\x0e\x08\x02\x12\x002\x08\x00\x00\x00\x00W\x0b\x86?"j\x08!\x12\x07predict\x1a$a2dccadc-2d52-4bc6-bbb7-2d2afe463c17"5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04(\x01q\x04sb\x85q\x05.\x80\x03}q\x00.': b'\x80\x03cg'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'oogl'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'e.pr'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'otob'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'uf.e'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'mpty'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'_pb2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\nEmp'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'ty\nq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x00)Rq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x01}q\x02'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'X\n\x00\x00'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x00ser'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'iali'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'zedq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x03C\x00q'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x04sb.',
             b'\x80\x03chydro_serving_grpc.monitoring.api_pb2\nExecutionInformation\nq\x00)Rq\x01}q\x02X\n\x00\x00\x00serializedq\x03B;\x01\x00\x00\n\xb1\x01\n@\n5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04\x1a\x07predict\x12\x1f\n\rVMail Message\x12\x0e\x08\x02\x12\x002\x08\x00\x00\x00\x00\x00\x009@\x12\x1a\n\x0eAccount Length\x12\x08\x08\t\x12\x00R\x02\x84\x01\x12\x1a\n\x08Day Mins\x12\x0e\x08\x02\x12\x002\x08\xcd\xcc\xcc\xcc\xccL\\@\x12\x14\n\tDay Calls\x12\x07\x08\t\x12\x00R\x01`\x1a\x19\n\x17\n\x05Churn\x12\x0e\x08\x02\x12\x002\x08\x00\x00\x00\x00W\x0b\x86?"j\x08!\x12\x07predict\x1a$a2dccadc-2d52-4bc6-bbb7-2d2afe463c17"5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04(\x01q\x04sb\x85q\x05.\x80\x03}q\x00.': b'\x80\x03cg'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'oogl'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'e.pr'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'otob'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'uf.e'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'mpty'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'_pb2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\nEmp'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'ty\nq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x00)Rq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x01}q\x02'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'X\n\x00\x00'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x00ser'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'iali'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'zedq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x03C\x00q'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                b'\x04sb.',
             b'\x80\x03chydro_serving_grpc.monitoring.api_pb2\nExecutionInformation\nq\x00)Rq\x01}q\x02X\n\x00\x00\x00serializedq\x03B;\x01\x00\x00\n\xb1\x01\n@\n5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04\x1a\x07predict\x12\x1f\n\rVMail Message\x12\x0e\x08\x02\x12\x002\x08\x9a\x99\x99\x99\x99\x99\xb9?\x12\x1a\n\x0eAccount Length\x12\x08\x08\t\x12\x00R\x02\xba\x01\x12\x1a\n\x08Day Mins\x12\x0e\x08\x02\x12\x002\x08\x9a\x99\x99\x99\x999a@\x12\x14\n\tDay Calls\x12\x07\x08\t\x12\x00R\x01a\x1a\x19\n\x17\n\x05Churn\x12\x0e\x08\x02\x12\x002\x08\x00\x00\x00 \xe58\x90?"j\x08!\x12\x07predict\x1a$3e580a13-174e-4c43-9b77-1b51fff4086e"5DEMO-xgb-churn-pred-model-monitor-2020-03-11-12-25-04(\x01q\x04sb\x85q\x05.\x80\x03}q\x00.': b'\x80\x03cg'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'oogl'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'e.pr'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'otob'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'uf.e'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'mpty'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'_pb2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\nEmp'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'ty\nq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x00)Rq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x01}q\x02'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'X\n\x00\x00'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x00ser'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'iali'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'zedq'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x03C\x00q'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               b'\x04sb.'}}